version: "3.7"
services:
  postgres:
    image: postgres:12
    ports:
      - 55432:5432
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  #        volumes:
  #            - db-volume:/var/lib/postgresql/data

  nginx:
    build:
      context: docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "${API_EXTERNAL_PORT}:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker
      dockerfile: development/php-fpm/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    env_file:
      - .env
      - app/.env
    environment:
      DATABASE_URL: "pgsql://postgres:postgres@postgres:5432/test?server_version=12&charset=utf8"
    volumes:
      - ./app:/app
    depends_on:
      - postgres

  php-cli:
    build:
      context: docker
      dockerfile: development/php-cli/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    env_file:
      - .env
      - app/.env
    environment:
      DATABASE_URL: "pgsql://postgres:postgres@postgres:5432/test?server_version=12&charset=utf8"
    volumes:
      - ./app:/app

  php-cli-root:
    build:
      context: docker
      dockerfile: development/php-cli/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    env_file:
      - .env
    volumes:
      - .:/app

#volumes:
#  db-volume:
