version: "3.7"
services:

  nginx:
    image: nalcheg/nginx-php-fpm-app-public
#    build:
#      context: docker
#      dockerfile: development/nginx/Dockerfile
    networks:
      - default
    volumes:
      - ./app:/app
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker
      dockerfile: development/php-fpm/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    env_file:
      - .env
      - app/.env
    networks:
      - default
      - infranet
    volumes:
      - ./app:/app

  php-cli:
    build:
      context: docker
      dockerfile: development/php-xdebug-cli/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    env_file:
      - .env
      - app/.env
    networks:
      - default
      - infranet
    volumes:
      - ./app:/app

  php-cli-root:
    build:
      context: docker
      dockerfile: development/php-cli/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    env_file:
      - .env
    networks:
      - default
    volumes:
      - .:/app

networks:
  default:
  infranet:
    external:
      name: infranet
